#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run check-format || 
( echo '🤢🤮🤢🤮 styling looks disgusting. 🤢🤮🤢🤮
    Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

npm run lint || 
(  echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
    ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)

npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
    Are you seriously trying to write that? Make the changes required above.'
    false;
)
